export const ERROR_CODES = {
  // VALIDATON & GENERIC
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  IDEMPOTENCY_KEY_MISSING: 'IDEMPOTENCY_KEY_MISSING',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  FORBIDDEN: 'FORBIDDEN',

  // AUTH - BASE
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_REFRESH_INVALID: 'AUTH_REFRESH_INVALID',
  AUTH_GOOGLE_EXCHANGE_FAILED: 'AUTH_GOOGLE_EXCHANGE_FAILED',
  AUTH_GOOGLE_PROFILE_INVALID: 'AUTH_GOOGLE_PROFILE_INVALID',
  AUTH_OAUTH_STATE_MISMATCH: 'AUTH_OAUTH_STATE_MISMATCH',

  // AUTH - OTP
  AUTH_OTP_INVALID: 'AUTH_OTP_INVALID',
  AUTH_OTP_EXPIRED: 'AUTH_OTP_EXPIRED',
  AUTH_OTP_RATE_LIMITED: 'AUTH_OTP_RATE_LIMITED',
  AUTH_OTP_MAX_ATTEMPTS: 'AUTH_OTP_MAX_ATTEMPTS',
  AUTH_OTP_PURPOSE_MISMATCH: 'AUTH_OTP_PUPOSE_MISMATCH',

  // AUTH - MAGIC LINK
  AUTH_MAGIC_LINK_INVALID: 'AUTH_MAGIC_LINK_INVALID',
  AUTH_MAGIC_LINK_EXPIRED: 'AUTH_MAGIC_LINK_EXPIRED',
  AUTH_MAGIC_LINK_RATE_LIMITED: 'AUTH_MAGIC_LINK_RATE_LIMITED',
  AUTH_MAGIC_LINK_PURPOSE_MISSMATCH: 'AUTH_MAGIC_LINK_PUPOSE_MISSMATCH',

  // AUTH - SESSION
  AUTH_SESSION_NOT_FOUND: 'AUTH_SESSION_NOT_FOUND',
  AUTH_SESSION_REVOKED: 'AUTH_SESSION_REVOKED',
  AUTH_SESSION_THEFT_DETECTED: 'AUTH_SESSION_THEFT_DETECTED',

  // AUTH - 2FA
  AUTH_2FA_REQUIRED: 'AUTH_2FA_REQUIRED',
  AUTH_2FA_INVALID: 'AUTH_2FA_INVALID',
  AUTH_2FA_ALREADY_ENABLED: 'AUTH_2FA_ALREADY_ENABLED',
  AUTH_2FA_NOT_ENABLED: 'AUTH_2FA_NOT_ENABLED',
  AUTH_2FA_BACKUP_CODE_USED: 'AUTH_2FA_BACKUP_CODE_USED',
  AUTH_2FA_BACKUP_CODE_INVALID: 'AUTH_2FA_BACKUP_CODE_INVALID',
  AUTH_ELEVATED_SESSION_REQUIRED: 'AUTH_ELEVATED_SESSION_REQUIRED',

  // AUTH - EMAIL DELIVERY
  AUTH_EMAIL_DELIVERY_FAILED: 'AUTH_EMAIL_DELIVERY_FAILED',

  // USER
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_CONFLICT: 'USER_EMAIL_CONFLICT',
  USER_SUSPENDED: 'USER_SUSPENDED',
  USER_INVALID_PASSWORD: 'USER_INVALID_PASSWORD',
  USER_CONTACT_NOT_FOUND: 'USER_CONTACT_NOT_FOUND',
  USER_INVALID_ROLE: 'USER_INVALID_ROLE',
  USER_INVALID_OUTLET_ASSIGNMENT: 'USER_INVALID_OUTLET_ASSIGNMENT',
  USER_OUTLET_NOT_FOUND: 'USER_OUTLET_NOT_FOUND',

  // CATEGORY
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_SLUG_TAKEN: 'CATEGORY_SLUG_TAKEN',
  CATEGORY_REORDER_LEVEL_MISMATCH: 'CATEGORY_REORDER_LEVEL_MISMATCH',

  // BRAND
  BRAND_NOT_FOUND: 'BRAND_NOT_FOUND',

  // STORAGE
  STORAGE_OBJECT_NOT_FOUND: 'STORAGE_OBJECT_NOT_FOUND',
  STORAGE_OBJECT_UNREADABLE: 'STORAGE_OBJECT_UNREADABLE',

  // MEDIA / IMAGE
  IMAGE_INVALID: 'IMAGE_INVALID',
  IMAGE_UNSUPPORTED_TYPE: 'IMAGE_UNSUPPORTED_TYPE',

  // INVOICE
  INVOICE_NOT_FOUND: 'INVOICE_NOT_FOUND',
  INVOICE_PDF_GENERATION_FAILED: 'INVOICE_PDF_GENERATION_FAILED',
  INVOICE_INVALID_STATUS_TRANSITION: 'INVOICE_INVALID_STATUS_TRANSITION',
  INVOICE_INVALID_PAYMENT: 'INVOICE_INVALID_PAYMENT',

  // ATTRIBUTE
  ATTRIBUTE_NOT_FOUND: 'ATTRIBUTE_NOT_FOUND',
  ATTRIBUTE_VALUE_NOT_FOUND: 'ATTRIBUTE_VALUE_NOT_FOUND',
  ATTRIBUTE_NAME_CONFLICT: 'ATTRIBUTE_NAME_CONFLICT',
  ATTRIBUTE_VALUE_CONFLICT: 'ATTRIBUTE_VALUE_CONFLICT',

  // PRODUCT
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_SLUG_CONFLICT: 'PRODUCT_SLUG_CONFLICT',
  PRODUCT_MEDIA_NOT_FOUND: 'PRODUCT_MEDIA_NOT_FOUND',
  PRODUCT_MEDIA_NOT_OWNED: 'PRODUCT_MEDIA_NOT_OWNED',

  // PRODUCT VARIANT
  VARIANT_NOT_FOUND: 'VARIANT_NOT_FOUND',
  VARIANT_SKU_CONFLICT: 'VARIANT_SKU_CONFLICT',
  VARIANT_ATTRIBUTE_INVALID: 'VARIANT_ATTRIBUTE_INVALID',

  // PRODUCT DISCOUNT
  DISCOUNT_NOT_FOUND: 'DISCOUNT_NOT_FOUND',
  DISCOUNT_INVALID: 'DISCOUNT_INVALID',

  // OUTLET
  OUTLET_NOT_FOUND: 'OUTLET_NOT_FOUND',
  OUTLET_CODE_CONFLICT: 'OUTLET_CODE_CONFLICT',
  OUTLET_INACTIVE: 'OUTLET_INACTIVE',
  OUTLET_INVENTORY_NOT_FOUND: 'OUTLET_INVENTORY_NOT_FOUND',
  OUTLET_INVENTORY_INVALID: 'OUTLET_INVENTORY_INVALID',

  // CART
  CART_NOT_FOUND: 'CART_NOT_FOUND',
  CART_EMPTY: 'CART_EMPTY',
  CART_OUTLET_NOT_SET: 'CART_OUTLET_NOT_SET',
  CART_ITEM_NOT_FOUND: 'CART_ITEM_NOT_FOUND',
  CART_STOCK_INSUFFICIENT: 'CART_STOCK_INSUFFICIENT',

  // ORDER
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_UNFULFILLABLE: 'ORDER_UNFULFILLABLE',
  ORDER_OUTLET_NOT_ELIGIBLE: 'ORDER_OUTLET_NOT_ELIGIBLE',
  ORDER_CONTACT_NOT_FOUND: 'ORDER_CONTACT_NOT_FOUND',
  ORDER_INVALID_STATUS_TRANSITION: 'ORDER_INVALID_STATUS_TRANSITION',
  ORDER_STOCK_RESERVATION_FAILED: 'ORDER_STOCK_RESERVATION_FAILED',

  // SUPPLIER
  SUPPLIER_NOT_FOUND: 'SUPPLIER_NOT_FOUND',
  SUPPLIER_CODE_CONFLICT: 'SUPPLIER_CODE_CONFLICT',

  // PURCHASE ORDER / GOODS RECEIPT
  PURCHASE_ORDER_NOT_FOUND: 'PURCHASE_ORDER_NOT_FOUND',
  PURCHASE_ORDER_INVALID_STATUS: 'PURCHASE_ORDER_INVALID_STATUS',
  PURCHASE_ORDER_EMPTY: 'PURCHASE_ORDER_EMPTY',
  PURCHASE_ORDER_ITEM_NOT_FOUND: 'PURCHASE_ORDER_ITEM_NOT_FOUND',
  PURCHASE_ORDER_ITEM_CONFLICT: 'PURCHASE_ORDER_ITEM_CONFLICT',
  PURCHASE_ORDER_RECEIPT_INVALID: 'PURCHASE_ORDER_RECEIPT_INVALID',

  // STOCK TRANSFER
  TRANSFER_NOT_FOUND: 'TRANSFER_NOT_FOUND',
  TRANSFER_INVALID_STATUS: 'TRANSFER_INVALID_STATUS',
  TRANSFER_SAME_OUTLET: 'TRANSFER_SAME_OUTLET',
  TRANSFER_ITEM_INVALID: 'TRANSFER_ITEM_INVALID',
  TRANSFER_STOCK_INSUFFICIENT: 'TRANSFER_STOCK_INSUFFICIENT',

  // PAYMENT
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_SIGNATURE_INVALID: 'PAYMENT_SIGNATURE_INVALID',
  PAYMENT_ORDER_NOT_PAYABLE: 'PAYMENT_ORDER_NOT_PAYABLE',
  PAYMENT_AMOUNT_MISMATCH: 'PAYMENT_AMOUNT_MISMATCH',
  PAYMENT_PROVIDER_UNSUPPORTED: 'PAYMENT_PROVIDER_UNSUPPORTED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
