export const ERROR_CODES = {
  // VALIDATON & GENERIC
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  IDEMPOTENCY_KEY_MISSING: 'IDEMPOTENCY_KEY_MISSING',
  FORBIDDEN: 'FORBIDDEN',

  // AUTH - BASE
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_REFRESH_INVALID: 'AUTH_REFRESH_INVALID',
  AUTH_GOOGLE_EXCHANGE_FAILED: 'AUTH_GOOGLE_EXCHANGE_FAILED',
  AUTH_GOOGLE_PROFILE_INVALID: 'AUTH_GOOGLE_PROFILE_INVALID',
  AUTH_OAUTH_STATE_MISMATCH: 'AUTH_OAUTH_STATE_MISMATCH',

  // AUTH - OTP
  AUTH_OTP_INVALID: 'AUTH_OTP_INVALID',
  AUTH_OTP_EXPIRED: 'AUTH_OTP_EXPIRED',
  AUTH_OTP_RATE_LIMITED: 'AUTH_OTP_RATE_LIMITED',
  AUTH_OTP_MAX_ATTEMPTS: 'AUTH_OTP_MAX_ATTEMPTS',
  AUTH_OTP_PUPOSE_MISSMATCH: 'AUTH_OTP_PUPOSE_MISMATCH',

  // AUTH - MAGIC LINK
  AUTH_MAGIC_LINK_INVALID: 'AUTH_MAGIC_LINK_INVALID',
  AUTH_MAGIC_LINK_EXPIRED: 'AUTH_MAGIC_LINK_EXPIRED',
  AUTH_MAGIC_LINK_RATE_LIMITED: 'AUTH_MAGIC_LINK_RATE_LIMITED',
  AUTH_MAGIC_LINK_PUPOSE_MISSMATCH: 'AUTH_MAGIC_LINK_PUPOSE_MISSMATCH',

  // AUTH - SESSION
  AUTH_SESSION_NOT_FOUND: 'AUTH_SESSION_NOT_FOUND',
  AUTH_SESSION_REVOKED: 'AUTH_SESSION_REVOKED',
  AUTH_SESSION_THEFT_DETECTED: 'AUTH_SESSION_THEFT_DETECTED',

  // AUTH - 2FA
  AUTH_2FA_REQUIRED: 'AUTH_2FA_REQUIRED',
  AUTH_2FA_INVALID: 'AUTH_2FA_INVALID',
  AUTH_2FA_ALREADY_ENABLED: 'AUTH_2FA_ALREADY_ENABLED',
  AUTH_2FA_NOT_ENABLED: 'AUTH_2FA_NOT_ENABLED',
  AUTH_2FA_BACKUP_CODE_USED: 'AUTH_2FA_BACKUP_CODE_USED',
  AUTH_2FA_BACKUP_CODE_INVALID: 'AUTH_2FA_BACKUP_CODE_INVALID',
  AUTH_ELEVATED_SESSION_REQUIRED: 'AUTH_ELEVATED_SESSION_REQUIRED',

  // AUTH - EMAIL DELIVERY
  AUTH_EMAIL_DELIVERY_FAILED: 'AUTH_EMAIL_DELIVERY_FAILED',

  // USER
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_CONFLICT: 'USER_EMAIL_CONFLICT',
  USER_SUSPENDED: 'USER_SUSPENDED',

  // CATEGORY
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_SLUG_TAKEN: 'CATEGORY_SLUG_TAKEN',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
